export function createEventsRepositoryMock(
  overrides: Record<string, jest.Mock> = {},
) {
  return {
    asPrisma: jest.fn(),
    findEventTypeByIdForWrite: jest.fn(),
    findEventTypeByNameInChannel: jest.fn(),
    findEventByEventTypeId: jest.fn(),
    activateEventType: jest.fn(),
    createEventTypeInline: jest.fn(),
    findEventTypeName: jest.fn(),
    createEvent: jest.fn(),
    upsertUpcomingVenueConfig: jest.fn(),
    findPublicEventsForSection: jest.fn(),
    findPublicUpcomingHubEvents: jest.fn(),
    groupActiveClassSessionsByEvent: jest.fn(),
    findHubVenueConfigs: jest.fn(),
    findContactLineEvents: jest.fn(),
    findOrphanBookingEventTypes: jest.fn(),
    findPublicCatalogEventById: jest.fn(),
    findAdminEvents: jest.fn(),
    findAdminEventById: jest.fn(),
    findEventForUpdate: jest.fn(),
    findDuplicateEventTypeName: jest.fn(),
    renameEventType: jest.fn(),
    updateEvent: jest.fn(),
    findEventForDelete: jest.fn(),
    findVenueConfigTemplateId: jest.fn(),
    findGalleryPhotoIdsForEvent: jest.fn(),
    deleteEvent: jest.fn(),
    countVenueConfigsForTemplate: jest.fn(),
    deleteReservationEventTemplate: jest.fn(),
    deleteReservationTemplateIfUnlinked: jest.fn(),
    getEventDeleteGuardCounts: jest.fn(),
    countBookingsForEvent: jest.fn(),
    getOrphanEventTypeCounts: jest.fn(),
    findEventTypeContactInquiryCode: jest.fn(),
    deleteEventType: jest.fn(),
    deleteOrphanInlineEventType: jest.fn(),
    createBookingEventType: jest.fn(),
    findEventTypeAdminById: jest.fn(),
    findPublicBookingEventTypes: jest.fn(),
    findAdminEventTypes: jest.fn(),
    findEventTypeId: jest.fn(),
    updateEventType: jest.fn(),
    getEventTypeUsageCounts: jest.fn(),
    findAdminOccasionTypes: jest.fn(),
    createOccasionType: jest.fn(),
    findOccasionTypeId: jest.fn(),
    updateOccasionType: jest.fn(),
    deleteOccasionType: jest.fn(),
    countBookingsForOccasion: jest.fn(),
    findActiveOccasionIds: jest.fn(),
    clearOccasionAssignments: jest.fn(),
    replaceOccasionAssignments: jest.fn(),
    ...overrides,
  };
}
