export {
  AGENDA_HUB_PATH,
  AGENDAR_PATH,
  AGENDA_DISPONIBILIDAD_PATH,
  AGENDA_MI_AGENDA_PATH,
  AGENDA_PETICIONES_PATH,
  AGENDA_PAYMENT_HISTORY_PATH,
  AGENDA_BOX_OFFICE_PATH,
  AGENDA_STRIPE_WEBHOOKS_PATH,
} from "@/lib/admin/routes";
