export const FIXED_EVENT_PACKAGE_ERROR_CODES = {
  PACKAGE_REQUIRED: 'PACKAGE_REQUIRED',
  PACKAGE_NOT_APPLICABLE: 'PACKAGE_NOT_APPLICABLE',
  PACKAGE_NOT_FOUND: 'PACKAGE_NOT_FOUND',
  PACKAGE_INACTIVE: 'PACKAGE_INACTIVE',
  PACKAGE_SOLD_OUT: 'PACKAGE_SOLD_OUT',
  PACKAGE_CAPACITY_CONFLICT: 'PACKAGE_CAPACITY_CONFLICT',
  PACKAGE_HAS_SALES: 'PACKAGE_HAS_SALES',
  PACKAGES_EMPTY: 'PACKAGES_EMPTY',
  PACKAGES_SEATING_CONFLICT: 'PACKAGES_SEATING_CONFLICT',
  PACKAGE_ARRIVAL_INVALID: 'PACKAGE_ARRIVAL_INVALID',
} as const;

export type FixedEventPackageErrorCode =
  (typeof FIXED_EVENT_PACKAGE_ERROR_CODES)[keyof typeof FIXED_EVENT_PACKAGE_ERROR_CODES];

export function packageErrorBody(
  code: FixedEventPackageErrorCode,
  message: string,
  extra?: Record<string, unknown>,
) {
  return { code, message, ...extra };
}
