export const STRIPE_ENV_SECRET_KEY = 'STRIPE_SECRET_KEY';
export const STRIPE_ENV_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET';
export const STRIPE_ENV_PUBLISHABLE_KEY = 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY';
export const STRIPE_ENV_FRONTEND_URL = 'FRONTEND_URL';
export const STRIPE_ENV_NODE_ENV = 'NODE_ENV';

export const STRIPE_DEFAULT_FRONTEND_URL = 'http://localhost:3000';
